# Generated by Django 5.2.7 on 2025-10-17 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «Романтика», «Полевой букет», «VIP-сборка»', max_length=200, verbose_name='Название букета')),
                ('description', models.TextField(blank=True, help_text='Состав, особенности, повод для подарка', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (в рублях)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bouquets/', verbose_name='Изображение букета')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать в каталоге')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
                'ordering': ['name'],
            },
        ),
    ]
